apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.postgres.replicas }}
  imageName: ghcr.io/cloudnative-pg/postgresql:{{ .Values.postgres.version }}

  storage:
    size: {{ .Values.postgres.storage.size }}
    storageClass: {{ .Values.postgres.storage.className }}
  
  certificates:
    serverTLSSecret: "{{ .Release.Name }}-wildcard-tls"
    serverCASecret: "{{ .Release.Name }}-wildcard-tls"
  
  postgresql:
    parameters:
      ssl_ciphers: "HIGH:!aNULL:!MD5"

  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required

  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.user }}

  podSecurityContext:
    fsGroup: 26         # 26 is the default postgres UID/GID in CNPG
    fsGroupChangePolicy: "Always"
