apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    # CNPG automatically flags the current primary/master database replica pod with this label
    cnpg.io/cluster: {{ .Release.Name }}-db
    role: primary
  ports:
    - protocol: TCP
      port: 5432        # The internal cluster port
      targetPort: 5432  # The port inside the Postgres container
      nodePort: {{ .Values.postgres.nodePort }} # The explicit host-level network boundary entryway
