apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wildcard-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  # The values will be passed as base64 strings from your values.yaml or secrets provider
  ca.crt: {{ .Values.tls.ca_certificate | quote }}
  tls.crt: {{ .Values.tls.certificate | quote }}
  tls.key: {{ .Values.tls.privateKey | quote }}
